# Generated by Django 5.1.1 on 2024-10-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение продукта",
                null=True,
                upload_to="../media/photos",
                verbose_name="Изображение",
            ),
        ),
    ]
