# Generated by Django 5.1.1 on 2024-10-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                help_text="Введите дату создания продукта",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                auto_now=True,
                help_text="Введите дату изменения продукта",
                verbose_name="Дата изменения",
            ),
        ),
    ]
