# Generated by Django 5.1.1 on 2024-10-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="videos",
            field=models.FileField(
                blank=True, null=True, upload_to="media/videos", verbose_name="Видео"
            ),
        ),
    ]
