# Generated by Django 5.1.1 on 2024-11-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name", "price"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
